services:
    marttiphpbb.customcode.listener:
        class: marttiphpbb\customcode\event\main_listener
        arguments:
            - @request
            - @template
            - %core.root_path%
        tags:
            - { name: event.listener }

            
            
